### ISSUE TITLE
一般用图库

### ISSUE THREAD

**Issue by bakasine** [bakasine/gallery#1]

**Comment by uerax** [comment]
<img width="568" alt="image" src="https://github.com/bakasine/gallery/assets/44748971/2b50de2c-b98d-4667-a947-9977332c1d5e">

**Comment by uerax** [comment]
<img width="553" alt="image" src="https://github.com/bakasine/gallery/assets/44748971/cbb9adc9-b47b-410c-9759-8b4ae33790cb">
